version: 1

requiredChecks:
  - test
  - lint

payout:
  mode: tiered
  tiers:
    - name: docs
      amountUsd: 1
      match:
        onlyPaths:
          - 'README.md'
          - 'docs/**'
    - name: simple_fix
      amountUsd: 5
      match:
        maxFilesChanged: 5
        maxAdditions: 60
        maxDeletions: 60
    - name: feature
      amountUsd: 20
      match:
        maxFilesChanged: 15
        maxAdditions: 300
        maxDeletions: 200
    - name: security_patch
      amountUsd: 50
      match:
        anyPaths:
          - 'src/auth/**'
          - 'src/crypto/**'
          - 'security/**'

holdIf:
  - rule: touchesPaths
    any:
      - '.github/workflows/**'
      - 'package-lock.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
  - rule: newDependencies
  - rule: coverageDrop
    gtPercent: 2

addressClaim:
  mode: pr_comment
  command: '/gitpay address'
