/**
 * OSM402 bot comment templates for GitHub issues and PRs.
 * All comments include hashes, tx links, and amounts.
 */

import { activeChain, txExplorerUrl, addressExplorerUrl } from '../config/chains.js';

function txLink(txHash: string): string {
  return `[${txHash.slice(0, 10)}...](${txExplorerUrl(txHash)})`;
}

function addressLink(address: string): string {
  return `[${address.slice(0, 10)}...](${addressExplorerUrl(address)})`;
}

/**
 * Comment posted when a bounty label is detected (issue created, funding pending)
 */
export function fundingPendingComment(params: {
  amountUsd: number;
  escrowAddress: string;
  chainId: number;
}): string {
  return [
    `### OSM402 — Bounty Detected`,
    '',
    `| Field | Value |`,
    `|-------|-------|`,
    `| Amount | ${params.amountUsd} ${activeChain.assetSymbol} |`,
    `| Escrow | ${addressLink(params.escrowAddress)} |`,
    `| Chain | ${activeChain.name} (${params.chainId}) |`,
    `| Status | Funding pending |`,
    '',
    `> Fund this bounty by sending an x402 payment to \`POST /api/fund\`.`,
  ].join('\n');
}

/**
 * Comment posted when escrow is funded via x402 payment
 */
export function fundedComment(params: {
  amountUsd: number;
  escrowAddress: string;
  intentHash: string;
  depositTxHash?: string;
  chainId: number;
}): string {
  const txLine = params.depositTxHash
    ? `| Deposit TX | ${txLink(params.depositTxHash)} |`
    : `| Deposit TX | pending |`;

  return [
    `### OSM402 — Funded`,
    '',
    `| Field | Value |`,
    `|-------|-------|`,
    `| Cap | ${params.amountUsd} ${activeChain.assetSymbol} |`,
    `| Escrow | ${addressLink(params.escrowAddress)} |`,
    `| Intent Hash | \`${params.intentHash.slice(0, 18)}...\` |`,
    txLine,
    `| Chain | ${activeChain.name} (${params.chainId}) |`,
    '',
    `> Escrow is funded. Submit a PR referencing this issue to claim the bounty.`,
  ].join('\n');
}

/**
 * Comment posted when payout is executed successfully
 */
export function paidComment(params: {
  amountUsd: number;
  recipient: string;
  txHash: string;
  cartHash: string;
  intentHash: string;
  mergeSha: string;
}): string {
  return [
    `### OSM402 — Paid`,
    '',
    `| Field | Value |`,
    `|-------|-------|`,
    `| Amount | ${params.amountUsd} ${activeChain.assetSymbol} |`,
    `| Recipient | ${addressLink(params.recipient)} |`,
    `| TX | ${txLink(params.txHash)} |`,
    `| Cart Hash | \`${params.cartHash.slice(0, 18)}...\` |`,
    `| Intent Hash | \`${params.intentHash.slice(0, 18)}...\` |`,
    `| Merge SHA | \`${params.mergeSha.slice(0, 12)}\` |`,
  ].join('\n');
}

/**
 * Comment posted when payout is held for manual review
 */
export function holdComment(params: {
  amountUsd: number;
  reasons: string[];
  mergeSha: string;
}): string {
  const reasonList = params.reasons.map((r) => `- ${r}`).join('\n');

  return [
    `### OSM402 — HOLD`,
    '',
    `**Manual review required.**`,
    '',
    `| Field | Value |`,
    `|-------|-------|`,
    `| Computed Amount | ${params.amountUsd} ${activeChain.assetSymbol} |`,
    `| Merge SHA | \`${params.mergeSha.slice(0, 12)}\` |`,
    '',
    `**Hold Reasons:**`,
    reasonList,
    '',
    `> A maintainer can override by adding the \`osm402:override\` label.`,
  ].join('\n');
}

/**
 * Comment posted with AI review analysis on a PR
 */
export function reviewComment(params: {
  summary: string[];
  riskFlags: string[];
  testObservations: string[];
  suggestedTier?: string;
  confidence: number;
  aiProvider?: string;
  aiModel?: string;
  aiSource?: 'gemini';
}): string {
  const lines = [
    `### OSM402 Review (Gemini)`,
    '',
    `| Field | Value |`,
    `|-------|-------|`,
    `| AI Engine | ${(params.aiProvider || 'gemini').toUpperCase()} (${params.aiModel || 'gemini-2.0-flash'}) |`,
    `| AI Source | live Gemini API |`,
    '',
    `**Summary:**`,
    ...params.summary.map((s) => `- ${s}`),
  ];

  if (params.riskFlags.length > 0) {
    lines.push('', `**Risk Flags:**`);
    lines.push(...params.riskFlags.map((f) => `- ${f}`));
  }

  if (params.testObservations.length > 0) {
    lines.push('', `**Test Observations:**`);
    lines.push(...params.testObservations.map((t) => `- ${t}`));
  }

  if (params.suggestedTier) {
    lines.push('', `**Suggested Tier:** ${params.suggestedTier}`);
  }

  lines.push('', `**Confidence:** ${(params.confidence * 100).toFixed(0)}%`);
  lines.push('', `> *This review was generated by AI and does not determine payout amounts.*`);

  return lines.join('\n');
}
